optional libjpeg-turbo support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -54,6 +54,7 @@ if is_windows; then
   TF_NEED_HDFS=0
   TF_NEED_CUDA=0
   TF_NEED_OPENCL=0
+  TF_NEED_LIBJPEG_TURBO=0
 fi
 
 while [ "$TF_NEED_GCP" == "" ]; do
@@ -99,6 +100,40 @@ while [ "$TF_NEED_HDFS" == "" ]; do
     * ) echo "Invalid selection: " $INPUT;;
   esac
 done
+
+while [ "$TF_NEED_LIBJPEG_TURBO" == "" ]; do
+  read -p "Do you wish to build TensorFlow with "\
+"libjpeg-turbo (2x faster than libjpeg but requires autoconf, automake, libtool, nasm)? [y/N] " INPUT
+  case $INPUT in
+    [Yy]* ) echo "Libjpeg-Turbo will replace Libjpeg for TensorFlow if dependencies are met."; TF_NEED_LIBJPEG_TURBO=1;;
+    [Nn]* ) echo "Libjpeg will be used instead of Libjpeg-Turbo."; TF_NEED_LIBJPEG_TURBO=0;;
+    * ) echo "Invalid selection: " $INPUT;;
+  esac
+done
+
+if [ $TF_NEED_LIBJPEG_TURBO == 1 ]; then
+  ALL_LJT_DEPS_MET=1;
+  for i in "autoconf" "automake" "libtool" "nasm"; do
+    hash $i 2>/dev/null || {
+      echo >&2 -e "\e[31mInstallation with libjpeg-turbo enabled requires $i" \
+      "to be installed on the operating system.\e[0m";
+      echo >&2 -e "\e[31mPlease install $i or select N for libjpeg-turbo" \
+      "(libjpeg will be used instead).\e[0m";
+      ALL_LJT_DEPS_MET=0;
+    }
+  done
+
+  if [ $ALL_LJT_DEPS_MET == 0 ]; then
+    echo -e "\e[31mAborting.\e[0m";
+    exit 1;
+  fi
+
+  echo "autoconf, automake, libtool, nasm dependencies met for libjpeg.turbo"
+  perl -pi -e "s,WITH_LIBJPEG_TURBO_SUPPORT = (False|True),WITH_LIBJPEG_TURBO_SUPPORT = True,s" tensorflow/core/platform/default/build_config.bzl
+
+else
+  perl -pi -e "s,WITH_LIBJPEG_TURBO_SUPPORT = (False|True),WITH_LIBJPEG_TURBO_SUPPORT = False,s" tensorflow/core/platform/default/build_config.bzl
+fi
 
 if [ "$TF_NEED_HDFS" == "1" ]; then
   # Update Bazel build configuration.
