Add ability to set gcc host compiler to configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+DO_NOT_SUBMIT_WARNING="Unofficial setting. DO NOT SUBMIT!!!"
+
 ## Set up python-related environment settings
 while true; do
   fromuser=""
@@ -41,6 +43,29 @@ if [ "$TF_NEED_CUDA" == "0" ]; then
   echo "Configuration finished"
   exit
 fi
+
+# Set up which gcc nvcc should use as the host compiler
+while true; do
+  fromuser=""
+  if [-z "$GCC_HOST_COMPILER_PATH"]; then
+    default_gcc_host_compiler_path=$(which gcc)
+    read -p "Please specify which gcc nvcc should use as the host compiler. [Default is $default_gcc_host_compiler]: " GCC_HOST_COMPILER_PATH
+    fromuser="1"
+    if [ -z "$GCC_HOST_COMPILER_PATH" ]; then
+      GCC_HOST_COMPILER_PATH=$default_gcc_host_compiler_path
+    fi
+  fi
+  if [ -e "$GCC_HOST_COMPILER_PATH" ]; then
+    break
+  fi
+  echo "Invalid gcc path. ${GCC_HOST_COMPILER_PATH} cannot be found" 1>&2
+  if [ -z "$fromuser" ]; then
+    exit 1
+  fi
+  GCC_HOST_COMPILER_PATH=""
+  # Retry
+done
+
 
 # Find out where the CUDA toolkit is installed
 while true; do
@@ -130,6 +155,11 @@ TF_CUDNN_VERSION=$TF_CUDNN_EXT
 
 EOF
 
+# Configure the gcc host compiler to use
+export WARNING=$DO_NOT_SUBMIT_WARNING
+perl -pi -e "s,CPU_COMPILER = \('.*'\),# ENV{WARNING}\nCPU_COMPILER = ('ENV{GCC_HOST_COMPILER_PATH}'),s" third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc
+perl -pi -e "s,GCC_HOST_COMPILER_PATH = \('.*'\),# ENV{WARNING}\nGCC_HOST_COMPILER_PATH = ('ENV{GCC_HOST_COMPILER_PATH}'),s" third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc
+
 # Configure the Cuda toolkit version to work with.
 perl -pi -e "s,CUDA_VERSION = '[0-9\.]*',CUDA_VERSION = '$TF_CUDA_EXT',s" tensorflow/core/platform/default/build_config.bzl
 perl -pi -e "s,(GetCudaVersion.*return )\"[0-9\.]*\",\1\"$TF_CUDA_EXT\",s" tensorflow/stream_executor/dso_loader.cc
@@ -172,7 +202,7 @@ EOF
 done
 
 if [ ! -z "$TF_CUDA_COMPUTE_CAPABILITIES" ]; then
-  export WARNING="Unofficial setting. DO NOT"" SUBMIT!!!"
+  export WARNING=$DO_NOT_SUBMIT_WARNING
   function CudaGenCodeOpts() {
     OUTPUT=""
     for CAPABILITY in $@; do
