Fix build issues and re-enable running benchmarks in cpu_benchmarks.yml
PiperOrigin-RevId: 725664749

diff --git a/third_party/xla/.github/workflows/cpu_benchmarks.yml b/third_party/xla/.github/workflows/cpu_benchmarks.yml
--- a/third_party/xla/.github/workflows/cpu_benchmarks.yml
+++ b/third_party/xla/.github/workflows/cpu_benchmarks.yml
@@ -69,67 +69,76 @@ jobs:
         uses: actions/checkout@v3
         with:
           repository: openxla/xla
+          path: openxla
 
       - name: Create results directory
-        working-directory: xla
+        working-directory: openxla
         run:
           mkdir results
 
-      - name: Run setup.sh for E2E benchmarks flax_2b
-        working-directory: xla/backends/cpu/benchmarks/e2e/gemma2/flax_2b
+      - name: Print machine specs
+        run: |
+          lscpu
+          free -h  # Memory information
+          df -h    # Disk space information
+          uname -a # Kernel information
+
+      - name: Run E2E benchmarks flax_2b
+        working-directory: openxla
         timeout-minutes: 60
         run: |
+          cd xla/backends/cpu/benchmarks/e2e/gemma2/flax_2b
           bash setup.sh
+          bash run.sh | tee -a ../../../../../../../results/flax_2b.log
 
-      - name: Run run.sh for E2E benchmarks flax_2b
-        working-directory: xla/backends/cpu/benchmarks/e2e/gemma2/flax_2b
-        timeout-minutes: 30
+      - name: Configure CPU backend
+        working-directory: openxla
         run: |
-          bash run.sh | tee -a ../../../../../../results/flax_2b.log
+          ./configure.py --backend=CPU
 
-      # TODO(juliagmt): Re-enable once the build is fixed.
-      # - name: Build run_hlo_module
-      #   working-directory: xla
-      #   run: bazel build -c opt --dynamic_mode=off //xla/tools:run_hlo_module
+      - name: Build run_hlo_module
+        working-directory: openxla
+        run: bazel build -c opt --dynamic_mode=off xla/tools:run_hlo_module
 
-      # - name: Run HLO Module Benchmarks
-      #   working-directory: xla
-      #   continue-on-error: true
-      #   run: |
-      #     for file in tests/fuzz/*.hlo; do
-      #       filename=$(basename "$file")
-      #       # Skip expected failed hlo files.
-      #       if [[ "$filename" == "rand_000060.hlo" || "$filename" == "rand_000067.hlo" || "$filename" == "rand_000072.hlo" ]]; then
-      #         echo "Skipping benchmark on $file"
-      #         continue
-      #       fi
-      #       echo "Running benchmark on $file"
-      #       ./bazel-bin/xla/tools/run_hlo_module --input_format=hlo --platform=CPU "$file"
-      #     done
+      - name: Run HLO Module Benchmarks
+        working-directory: openxla
+        continue-on-error: true
+        run: |
+          for file in xla/tests/fuzz/*.hlo; do
+            filename=$(basename "$file")
+            # Skip expected failed hlo files.
+            if [[ "$filename" == "rand_000060.hlo" || "$filename" == "rand_000067.hlo" || "$filename" == "rand_000072.hlo" ]]; then
+              echo "Skipping benchmark on $file"
+              continue
+            fi
+            echo "Running benchmark on $file"
+            ./bazel-bin/xla/tools/run_hlo_module --input_format=hlo --platform=CPU "$file"
+          done
 
-      # - name: Build CPU Benchmarks
-      #   working-directory: xla
-      #   run: bazel build -c opt --dynamic_mode=off //xla/backends/cpu/benchmarks:*
+      - name: Build CPU Benchmarks
+        working-directory: openxla
+        run: bazel build -c opt --dynamic_mode=off //xla/backends/cpu/benchmarks:*
 
-      # - name: Run CPU benchmarks
-      #   working-directory: xla
-      #   continue-on-error: true
-      #   run: |
-      #     find ./bazel-bin/xla/backends/cpu/benchmarks/ -maxdepth 1 -type f -executable -name "*_test" -print0 | while IFS= read -r -d $'\0' benchmark; do
-      #       benchmark_name=$(basename "$benchmark" | sed 's/_test$//') 
-      #       echo "Running benchmark: $benchmark_name"
+      - name: Run CPU benchmarks
+        working-directory: openxla
+        continue-on-error: true
+        run: |
+          find ./bazel-bin/xla/backends/cpu/benchmarks/ -maxdepth 1 -type f -executable -name "*_test" -print0 | while IFS= read -r -d $'\0' benchmark; do
+            benchmark_name=$(basename "$benchmark" | sed 's/_test$//') 
+            echo "Running benchmark: $benchmark_name"
 
-      #       # Run the benchmark with default parameters.
-      #       $benchmark --benchmark_filter=".*"
-      #       $benchmark --benchmark_filter=".*" > "results/$benchmark_name.log" 2>&1
+            # Run the benchmark with default parameters.
+            $benchmark --benchmark_filter=".*"
+            $benchmark --benchmark_filter=".*" > "results/$benchmark_name.log" 2>&1
 
-      #       # Check the exit code of the benchmark
-      #       if [ $? -ne 0 ]; then
-      #         echo "Error: Benchmark '$benchmark_name' failed. Check the log file: results/$benchmark_name.log"
-      #       else
-      #         echo "Benchmark '$benchmark_name' completed successfully."
-      #       fi
-      #     done
+            # Check the exit code of the benchmark
+            if [ $? -ne 0 ]; then
+              echo "Error: Benchmark '$benchmark_name' failed. Check the log file: results/$benchmark_name.log"
+            else
+              echo "Benchmark '$benchmark_name' completed successfully."
+            fi
+          done
+
       - name: Upload Results ${{ matrix.build_target }}
         uses: actions/upload-artifact@v4
         with:
